sudo: false
cache:
  directories:
    - $HOME/.cache/pip
language: python
python:
  - "3.6"
env:
  - DJANGO=django>=2.0,<3
  - DJANGO=django>=3.0,<4
install:
  - pip install -U pip pytest>=3.0.0
  - "pip install $DJANGO -e .[dev]"
script:
  - flake8 cavalry
  - py.test -vvv --cov .
after_success:
  - bash <(curl -s https://codecov.io/bash)
