name: build
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - python-version: '3.6'
            DJANGO: 'django>=2.0,<3'
          - python-version: '3.6'
            DJANGO: 'django>=3.0,<4'
          - python-version: '3.10'
            DJANGO: 'django>=4.0,<5'
    steps:
      - name: 'Set up Python ${{ matrix.python-version }}'
        uses: actions/setup-python@v2
        with:
          python-version: '${{ matrix.python-version }}'
      #- name: Cache multiple paths
      #  uses: actions/cache@v2
      #  with:
      #    path: $HOME/.cache/pip
      #    key: '${{ runner.os }}-${{ hashFiles(''TODO'') }}'
      - uses: actions/checkout@v2
      - run: pip install -U pip pytest>=3.0.0
      - run: 'pip install $DJANGO -e .[dev]'
        env:
          DJANGO: '${{ matrix.DJANGO }}'
      - run: flake8 cavalry
      - run: py.test -vvv --cov .
      - run: 'bash <(curl -s https://codecov.io/bash)'
